# Generated by Django 4.1.5 on 2023-01-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapi", "0002_blog_created_at_blog_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
